security:
    encoders:
        App\Entity\Admin:
            algorithm: bcrypt
        App\Entity\Prof:
            algorithm: bcrypt
        App\Entity\Etudiant:
            algorithm: bcrypt



    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        in_memory: { memory: ~ }

        chain_provider:
            chain:
                providers: [admin_provider, prof_provider, etudiant_provider]

        admin_provider:
            entity:
                class: App\Entity\Admin
                property: username

        prof_provider:
            entity:
                class: App\Entity\Prof
                property: username

        etudiant_provider:
            entity:
                class: App\Entity\Etudiant
                property: username
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            guard:
                provider: chain_provider
                authenticators:
                    - App\Security\LoginFormAuthAuthenticator

            logout:
                path: security_logout

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/prof, roles: ROLE_PROF }
         - { path: ^/etudiant, roles: ROLE_ETUDIANT }

    role_hierarchy:
        ROLE_ADMIN: ROLE_PROF